# The plugin gets its own service account, so a cache can grant it access by
# name.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "nix-store-csi.labels" . | nindent 4 }}
automountServiceAccountToken: false
